### ISSUE TITLE
Start and ending position offset 

### ISSUE THREAD

**Issue by achave11-ucsc** [achave11/brca-website#14]
Create a function and test that allows for internally making the -1 offset to satisfy the query at the request layer.

**Comment by david4096** [comment]
https://github.com/ga4gh/schemas/blob/7e586839dceb30c37c4a18ec09ad9bfab6a01b02/src/main/proto/ga4gh/variant_service.proto#L93

```
  // Required. The beginning of the window (0-based, inclusive) for
  // which overlapping variants should be returned.
  // Genomic positions are non-negative integers less than reference length.
  // Requests spanning the join of circular genomes are represented as
  // two requests one on each side of the join (position 0).
  int64 start = 4;

  // Required. The end of the window (0-based, exclusive) for which overlapping
  // variants should be returned.
  int64 end = 5;
```

**Comment by achave11-ucsc** [comment]
resent merge, also included the function which allowed for creating offset in two instances, to query the database, as well as illustrate the shift in the opposite direction when the request is being serviced. Reference issue #15
