### ISSUE TITLE
Datasets/search

### ISSUE THREAD

**Issue by david4096** [achave11/brca-website#16]
The metadata API endpoints is datasets/search. Only one dataset will be available.

**Comment by achave11-ucsc** [comment]
Okay, and what are the info-parameters required for this field? Are they the once we have build for the variantSet search & get responses we have build ? @david4096

**Comment by david4096** [comment]
Put in some boilerplate for now, they'll have some text we can copy over for the description. The info field can be left blank, just set a name and description. :)
