### ISSUE TITLE
GA4GH variant model with same data backing

### ISSUE THREAD

**Issue by david4096** [achave11/brca-website#3]
The current models includes a variant model that satisfies the needs for BRCA backend. We need to get at the same database table and convert the BRCA model into GA4GH (in code). This might be carried out with a controller.

**Comment by david4096** [comment]
This is `data/views`

**Comment by achave11-ucsc** [comment]
Improvements on issue #3 are provided by the closing of issue 6, but more changes are to be expected once the table denormalization is provided.

**Comment by achave11-ucsc** [comment]
@david4096 it seems like they have deployed a new DB. for us to just work with, although is not the one we will be using, will I get that by pulling from the new master? or their is another branch where I can get the beta version ?

**Comment by david4096** [comment]
I'm not sure, we can take a look together tomorrow.
